package source;


import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.Scanner;

import javax.imageio.ImageIO;


public class ImageLibrary {

    static Image DEFAULTSCREENPIC1;
    static Image DEFAULTSCREENPIC2;
    static Image Java1s;
    static Image Java2s;
    static Image Java3s;
    static Image Java4s;
    static Image Java5s;
    static Image Java6s;
    static Image app1s;
    static Image app2s;
    static Image app3s;
    static Image app4s;
    static Image app5s;
    static Image app6s;
    static Image app7s;
    static Image app8s;
    static Image app9s;
    static Image app10s;
    static Image app11s;
    static Image app12s;
    static Image app13s;
    static Image app14s;
    static Image pro1s;
    static Image pro2s;
    static Image pro3s;
    static Image pro4s;
    static Image pro5s;
    static Image pro6s;
    static Image pro7s;
    static Image pro8s;
    static Image pro9s;
    static Image pro10s;
    static Image pro11s;
    static Image pro12s;
    static Image pro13s;
    static Image pro14s;
    static Image Scratch1s;
    static Image Scratch2s;
    static Image Scratch3s;
    static Image Scratch4s;
    static Image Scratch5s;
    static Image Scratch6s;
    static Image Code1s;
    static Image Code2s;
    static Image Code3s;
    static Image Code4s;
    static Image Code5s;
    static Image Code6s;
    static Image Biomes1s;
    static Image Biomes2s;
    static Image Biomes3s;
    static Image Photo1s;
    static Image Photo2s;
    static Image Photo3s;
    static Image Photo4s;
    static Image Photo5s;
    static Image Photo6s;
    static Image Photo7s;
    static Image Photo8s;
    static Image Photo9s;
    static Image Photo10s;
    static Image Photo11s;
    static Image Photo12s;
    static Image Photo13s;
    static Image Photo14s;
    static Image Photo15s;
    static Image Skateboard1s;
    static Image Skateboard2s;
    static Image Skateboard3s;
    static Image Skateboard4s;
    static Image Skateboard5s;
    static Image Skateboard6s;
    static Image Skateboard7s;
    static Image Skateboard8s;
    static Image Skateboard9s;
    static Image Skateboard10s;
    static Image Skateboard11s;
    static Image Skateboard12s;
    static Image Skateboard13s;
    static Image Skateboard14s;
    static Image Skateboard15s;
    static Image Skateboard16s;
    static Image Skateboard17s;
    static Image Skateboard18s;
    static Image Skateboard19s;
    static Image Skateboard20s;
    static Image Skateboard21s;
    static Image Skateboard22s;
    static Image Skateboard23s;
    static Image Skateboard24s;
    static Image Skateboard25s;
    static Image Skateboard26s;
    static Image Skateboard27s;
    static Image Skateboard28s;
    static Image Skateboard29s;
    static Image Skateboard30s;
    static Image Skateboard31s;
    static Image Skateboard32s;
    static Image Skateboard33s;
    static Image Skateboard34s;
    static Image Skateboard35s;
    static Image Skateboard36s;
    static Image Skateboard37s;
    static Image Skateboard38s;
    static Image Skateboard39s;
    static Image ROV1s;
    static Image ROV2s;
    static Image ROV3s;
    static Image ROV4s;
    static Image ROV5s;
    static Image ROV6s;
    static Image ROV7s;
    static Image ROV8s;
    static Image ROV9s;
    static Image ROV10s;
    static Image ROV11s;
    static Image ROV12s;
    static Image ROV13s;
    static Image ROV14s;
    static Image ROV15s;
    static Image ROV16s;
    static Image ROV17s;
    static Image ROV18s;
    static Image ROV19s;
    static Image ROV20s;
    static Image ROV21s;
    static Image ROV22s;
    static Image ROV23s;
    static Image ROV24s;
    static Image ROV25s;
    static Image ROV26s;
    static Image ROV27s;
    static Image ROV28s;
    static Image ROV29s;
    static Image ROV30s;
    static Image ROV31s;
    static Image ROV32s;
    static Image ROV33s;
    static Image ROV34s;
    static Image ROV35s;
    static Image ROV36s;
    static Image Robo1s;
    static Image Robo2s;
    static Image Robo3s;
    static Image Robo4s;
    static Image Robo5s;
    static Image Robo6s;
    static Image Robo7s;
    static Image Robo8s;
    static Image Robo9s;
    static Image Robo10s;
    static Image Robo11s;
    static Image Robo12s;
    static Image Robo13s;
    static Image Robo14s;
    static Image Robo15s;
    static Image Robo16s;
    static Image Robo17s;
    static Image Robo18s;
    static Image ScratchW1s;
    static Image ScratchW2s;
    static Image ScratchW3s;
    static Image ScratchW4s;
    static Image ScratchW5s;
    static Image ScratchW6s;
    static Image ScratchW7s;
    static Image ScratchW8s;
    static Image ScratchW9s;
    static Image ScratchW10s;
    static Image ScratchW11s;
    static Image Math1s;
    static Image Math2s;
    static Image Math3s;
    static Image Art1s;
    static Image Art2s;
    static Image Art3s;
    static Image Art4s;
    static Image Art5s;
    static Image Art6s;
    static Image Robot1s;
    static Image Robot2s;
    static Image Robot3s;
    static Image Robot4s;
    static Image Robot5s;
    static Image Robot6s;
    static Image Robot7s;
    static Image Robot8s;
    static Image Robot9s;
    static Image Robot10s;
    static Image Robot11s;
    static Image Robot12s;
    static Image Robot13s;
    static Image Robot14s;
    static Image Robot15s;
    static Image Robot16s;
    static Image Robot17s;
    static Image Robot18s;
    static Image Robot19s;
    static Image Robot20s;
    static Image Robot21s;
    static Image Robot22s;
    static Image Robot23s;
    static Image Robot24s;
    static Image Robot25s;
    static Image Robot26s;
    static Image Robot27s;
    static Image Robot28s;
    static Image Robot29s;
    static Image Robot30s;
    static Image Robot31s;
    static Image Robot32s;
    static Image Robot33s;
    static Image Robot34s;
    static Image Robot35s;
    static Image Robot36s;
    static Image Robot37s;
    static Image Robot38s;
    static Image Robot39s;
    static Image Robot40s;
    static Image Robot41s;
    static Image Robot42s;
    static Image Robot43s;
    static Image Robot44s;
    static Image Robot45s;
    static Image Robot46s;
    static Image Robot47s;
    static Image Robot48s;
    static Image Robot49s;
    static Image Robot50s;
    static Image Robot51s;
    static Image Robot52s;
    static Image Robot53s;
    static Image Robot54s;
    static Image Robot55s;
    static Image Robot56s;
    static Image Robot57s;
    static Image Robot58s;
    static Image Robot59s;
    static Image Robot60s;
    static Image Robot61s;
    static Image Robot62s;
    static Image Robot63s;
    static Image Robot64s;
    static Image Robot65s;
    static Image Robot66s;
    static Image AppW1s;
    static Image AppW2s;
    static Image AppW3s;
    static Image AppW4s;
    static Image AppW5s;
    static Image AppW6s;
    static Image AppW7s;
    static Image AppW8s;
    static Image Java1;
    static Image Java2;
    static Image Java3;
    static Image Java4;
    static Image Java5;
    static Image Java6;





    int screenWidth = (int) Toolkit.getDefaultToolkit().getScreenSize().getWidth();
    int screenHeight = (int) Toolkit.getDefaultToolkit().getScreenSize().getHeight();

    public static final int textBoxSize = 100;



    /*
	 * this is where all the image files are stored. Add more images by making
	 * more variables and initializing them. In order to add images to the
	 * project, you must add them to the src/resources folder in the bottom left
	 * hand corner
	 * 
	 * 
	 * the image loading must use the loadImage method
	 */

    public ImageLibrary() {

        DEFAULTSCREENPIC1 = this.loadImage("/utils/REHSBackground.png").getScaledInstance(screenWidth,screenHeight,Image.SCALE_FAST);
        DEFAULTSCREENPIC2 = ImageLibrary.DEFAULTSCREENPIC1.getScaledInstance(screenWidth, screenHeight, Image.SCALE_FAST);//this.loadImage("/RANDOMPIC1.png");
        Java1 = this.loadImage("/introJava/Java1.JPG").getScaledInstance(screenWidth, screenHeight, Image.SCALE_FAST);
        Java2 = this.loadImage("/introJava/Java2.JPG").getScaledInstance(screenWidth, screenHeight, Image.SCALE_FAST);
        Java3 = this.loadImage("/introJava/Java3.JPG").getScaledInstance(screenWidth, screenHeight, Image.SCALE_FAST);
        Java4 = this.loadImage("/introJava/Java4.JPG").getScaledInstance(screenWidth, screenHeight, Image.SCALE_SMOOTH);
        Java5 = this.loadImage("/introJava/Java5.JPG").getScaledInstance(screenWidth, screenHeight, Image.SCALE_SMOOTH);
        Java6 = this.loadImage("/introJava/Java6.JPG").getScaledInstance(screenWidth, screenHeight, Image.SCALE_SMOOTH);

        Java1s = this.loadImage("/introductionJavaMini/Java1s.jpg");
        Java2s = this.loadImage("/introductionJavaMini/Java2s.jpg");
        Java3s = this.loadImage("/introductionJavaMini/Java3s.jpg");
        Java4s = this.loadImage("/introductionJavaMini/Java4s.jpg");
        Java5s = this.loadImage("/introductionJavaMini/Java5s.jpg");
        Java6s = this.loadImage("/introductionJavaMini/Java6s.jpg");
        app1s = this.loadImage("/appInventorMini/AppInventor1s.jpg");
        app2s = this.loadImage("/appInventorMini/AppInventor2s.jpg");
        app3s = this.loadImage("/appInventorMini/AppInventor3s.jpg");
        app4s = this.loadImage("/appInventorMini/AppInventor4s.jpg");
        app5s = this.loadImage("/appInventorMini/AppInventor5s.jpg");
        app6s = this.loadImage("/appInventorMini/AppInventor6s.jpg");
        app7s = this.loadImage("/appInventorMini/AppInventor7s.jpg");
        app8s = this.loadImage("/appInventorMini/AppInventor8s.jpg");
        app9s = this.loadImage("/appInventorMini/AppInventor9s.jpg");
        app10s = this.loadImage("/appInventorMini/AppInventor10s.jpg");
        app11s = this.loadImage("/appInventorMini/AppInventor11s.jpg");
        app12s = this.loadImage("/appInventorMini/AppInventor12s.jpg");
        app13s = this.loadImage("/appInventorMini/AppInventor13s.jpg");
        app14s = this.loadImage("/appInventorMini/AppInventor14s.jpg");
        pro1s = this.loadImage("/introductionPremiereProMini/PremierePro1s.jpg");
        pro2s = this.loadImage("/introductionPremiereProMini/PremierePro2s.jpg");
        pro3s = this.loadImage("/introductionPremiereProMini/PremierePro3s.jpg");
        pro4s = this.loadImage("/introductionPremiereProMini/PremierePro4s.jpg");
        pro5s = this.loadImage("/introductionPremiereProMini/PremierePro5s.jpg");
        pro6s = this.loadImage("/introductionPremiereProMini/PremierePro6s.jpg");
        pro7s = this.loadImage("/introductionPremiereProMini/PremierePro7s.jpg");
        pro8s = this.loadImage("/introductionPremiereProMini/PremierePro8s.jpg");
        pro9s = this.loadImage("/introductionPremiereProMini/PremierePro9s.jpg");
        pro10s = this.loadImage("/introductionPremiereProMini/PremierePro10s.jpg");
        pro11s = this.loadImage("/introductionPremiereProMini/PremierePro11s.jpg");
        pro12s = this.loadImage("/introductionPremiereProMini/PremierePro12s.jpg");
        pro13s = this.loadImage("/introductionPremiereProMini/PremierePro13s.jpg");
        pro14s = this.loadImage("/introductionPremiereProMini/PremierePro14s.jpg");
        Scratch1s = this.loadImage("/introductionScratchMini/Scratch1s.jpg");
        Scratch2s = this.loadImage("/introductionScratchMini/Scratch2s.jpg");
        Scratch3s = this.loadImage("/introductionScratchMini/Scratch3s.jpg");
        Scratch4s = this.loadImage("/introductionScratchMini/Scratch4s.jpg");
        Scratch5s = this.loadImage("/introductionScratchMini/Scratch5s.jpg");
        Scratch6s = this.loadImage("/introductionScratchMini/Scratch6s.jpg");
        Code1s = this.loadImage("/introductionPencilCodeMini/PencilCode1s.jpg");
        Code2s = this.loadImage("/introductionPencilCodeMini/PencilCode2s.jpg");
        Code3s = this.loadImage("/introductionPencilCodeMini/PencilCode3s.jpg");
        Code4s = this.loadImage("/introductionPencilCodeMini/PencilCode4s.jpg");
        Code5s = this.loadImage("/introductionPencilCodeMini/PencilCode5s.jpg");
        Code6s = this.loadImage("/introductionPencilCodeMini/PencilCode6s.jpg");
        Biomes1s = this.loadImage("/buildBiomesMini/Biomes1s.jpg");
        Biomes2s = this.loadImage("/buildBiomesMini/Biomes2s.jpg");
        Biomes3s = this.loadImage("/buildBiomesMini/Biomes3s.jpg");
        Photo1s = this.loadImage("/introductionPhotoshopMini/Photoshop1s.jpg");
        Photo2s = this.loadImage("/introductionPhotoshopMini/Photoshop2s.jpg");
        Photo3s = this.loadImage("/introductionPhotoshopMini/Photoshop3s.jpg");
        Photo4s = this.loadImage("/introductionPhotoshopMini/Photoshop4s.jpg");
        Photo5s = this.loadImage("/introductionPhotoshopMini/Photoshop5s.jpg");
        Photo6s = this.loadImage("/introductionPhotoshopMini/Photoshop6s.jpg");
        Photo7s = this.loadImage("/introductionPhotoshopMini/Photoshop7s.jpg");
        Photo8s = this.loadImage("/introductionPhotoshopMini/Photoshop8s.jpg");
        Photo9s = this.loadImage("/introductionPhotoshopMini/Photoshop9s.jpg");
        Photo10s = this.loadImage("/introductionPhotoshopMini/Photoshop10s.jpg");
        Photo11s = this.loadImage("/introductionPhotoshopMini/Photoshop11s.jpg");
        Photo12s = this.loadImage("/introductionPhotoshopMini/Photoshop12s.jpg");
        Photo13s = this.loadImage("/introductionPhotoshopMini/Photoshop13s.jpg");
        Photo14s = this.loadImage("/introductionPhotoshopMini/Photoshop14s.jpg");
        Photo15s = this.loadImage("/introductionPhotoshopMini/Photoshop15s.jpg");
        Skateboard1s = this.loadImage("/buildSkateboardMini/Skateboard1s.jpg");
        Skateboard2s = this.loadImage("/buildSkateboardMini/Skateboard2s.jpg");
        Skateboard3s = this.loadImage("/buildSkateboardMini/Skateboard3s.jpg");
        Skateboard4s = this.loadImage("/buildSkateboardMini/Skateboard4s.jpg");
        Skateboard5s = this.loadImage("/buildSkateboardMini/Skateboard5s.jpg");
        Skateboard6s = this.loadImage("/buildSkateboardMini/Skateboard6s.jpg");
        Skateboard7s = this.loadImage("/buildSkateboardMini/Skateboard7s.jpg");
        Skateboard8s = this.loadImage("/buildSkateboardMini/Skateboard8s.jpg");
        Skateboard9s = this.loadImage("/buildSkateboardMini/Skateboard9s.jpg");
        Skateboard10s = this.loadImage("/buildSkateboardMini/Skateboard10s.jpg");
        Skateboard11s = this.loadImage("/buildSkateboardMini/Skateboard11s.jpg");
        Skateboard12s = this.loadImage("/buildSkateboardMini/Skateboard12s.jpg");
        Skateboard13s = this.loadImage("/buildSkateboardMini/Skateboard13s.jpg");
        Skateboard14s = this.loadImage("/buildSkateboardMini/Skateboard14s.jpg");
        Skateboard15s = this.loadImage("/buildSkateboardMini/Skateboard15s.jpg");
        Skateboard16s = this.loadImage("/buildSkateboardMini/Skateboard16s.jpg");
        Skateboard17s = this.loadImage("/buildSkateboardMini/Skateboard17s.jpg");
        Skateboard18s = this.loadImage("/buildSkateboardMini/Skateboard18s.jpg");
        Skateboard19s = this.loadImage("/buildSkateboardMini/Skateboard19s.jpg");
        Skateboard20s = this.loadImage("/buildSkateboardMini/Skateboard20s.jpg");
        Skateboard21s = this.loadImage("/buildSkateboardMini/Skateboard21s.jpg");
        Skateboard22s = this.loadImage("/buildSkateboardMini/Skateboard22s.jpg");
        Skateboard23s = this.loadImage("/buildSkateboardMini/Skateboard23s.jpg");
        Skateboard24s = this.loadImage("/buildSkateboardMini/Skateboard24s.jpg");
        Skateboard25s = this.loadImage("/buildSkateboardMini/Skateboard25s.jpg");
        Skateboard26s = this.loadImage("/buildSkateboardMini/Skateboard26s.jpg");
        Skateboard27s = this.loadImage("/buildSkateboardMini/Skateboard27s.jpg");
        Skateboard28s = this.loadImage("/buildSkateboardMini/Skateboard28s.jpg");
        Skateboard29s = this.loadImage("/buildSkateboardMini/Skateboard29s.jpg");
        Skateboard30s = this.loadImage("/buildSkateboardMini/Skateboard30s.jpg");
        Skateboard31s = this.loadImage("/buildSkateboardMini/Skateboard31s.jpg");
        Skateboard32s = this.loadImage("/buildSkateboardMini/Skateboard32s.jpg");
        Skateboard33s = this.loadImage("/buildSkateboardMini/Skateboard33s.jpg");
        Skateboard34s = this.loadImage("/buildSkateboardMini/Skateboard34s.jpg");
        Skateboard35s = this.loadImage("/buildSkateboardMini/Skateboard35s.jpg");
        Skateboard36s = this.loadImage("/buildSkateboardMini/Skateboard36s.jpg");
        Skateboard37s = this.loadImage("/buildSkateboardMini/Skateboard37s.jpg");
        Skateboard38s = this.loadImage("/buildSkateboardMini/Skateboard38s.jpg");
        Skateboard39s = this.loadImage("/buildSkateboardMini/Skateboard39s.jpg");
        ROV1s = this.loadImage("/underwaterROVSMini/ROV1s.jpg");
        ROV2s = this.loadImage("/underwaterROVSMini/ROV2s.jpg");
        ROV3s = this.loadImage("/underwaterROVSMini/ROV3s.jpg");
        ROV4s = this.loadImage("/underwaterROVSMini/ROV4s.jpg");
        ROV5s = this.loadImage("/underwaterROVSMini/ROV5s.jpg");
        ROV6s = this.loadImage("/underwaterROVSMini/ROV6s.jpg");
        ROV7s = this.loadImage("/underwaterROVSMini/ROV7s.jpg");
        ROV8s = this.loadImage("/underwaterROVSMini/ROV8s.jpg");
        ROV9s = this.loadImage("/underwaterROVSMini/ROV9s.jpg");
        ROV10s = this.loadImage("/underwaterROVSMini/ROV10s.jpg");
        ROV11s = this.loadImage("/underwaterROVSMini/ROV11s.jpg");
        ROV12s = this.loadImage("/underwaterROVSMini/ROV12s.jpg");
        ROV13s = this.loadImage("/underwaterROVSMini/ROV13s.jpg");
        ROV14s = this.loadImage("/underwaterROVSMini/ROV14s.jpg");
        ROV15s = this.loadImage("/underwaterROVSMini/ROV15s.jpg");
        ROV16s = this.loadImage("/underwaterROVSMini/ROV16s.jpg");
        ROV17s = this.loadImage("/underwaterROVSMini/ROV17s.jpg");
        ROV18s = this.loadImage("/underwaterROVSMini/ROV18s.jpg");
        ROV19s = this.loadImage("/underwaterROVSMini/ROV19s.jpg");
        ROV20s = this.loadImage("/underwaterROVSMini/ROV20s.jpg");
        ROV21s = this.loadImage("/underwaterROVSMini/ROV21s.jpg");
        ROV22s = this.loadImage("/underwaterROVSMini/ROV22s.jpg");
        ROV23s = this.loadImage("/underwaterROVSMini/ROV23s.jpg");
        ROV24s = this.loadImage("/underwaterROVSMini/ROV24s.jpg");
        ROV25s = this.loadImage("/underwaterROVSMini/ROV25s.jpg");
        ROV26s = this.loadImage("/underwaterROVSMini/ROV26s.jpg");
        ROV27s = this.loadImage("/underwaterROVSMini/ROV27s.jpg");
        ROV28s = this.loadImage("/underwaterROVSMini/ROV28s.jpg");
        ROV29s = this.loadImage("/underwaterROVSMini/ROV29s.jpg");
        ROV30s = this.loadImage("/underwaterROVSMini/ROV30s.jpg");
        ROV31s = this.loadImage("/underwaterROVSMini/ROV31s.jpg");
        ROV32s = this.loadImage("/underwaterROVSMini/ROV32s.jpg");
        ROV33s = this.loadImage("/underwaterROVSMini/ROV33s.jpg");
        ROV34s = this.loadImage("/underwaterROVSMini/ROV34s.jpg");
        ROV35s = this.loadImage("/underwaterROVSMini/ROV35s.jpg");
        ROV36s = this.loadImage("/underwaterROVSMini/ROV36s.jpg");
        Robo1s = this.loadImage("/intermediateRoboticsMini/Robo1s.jpg");
        Robo2s = this.loadImage("/intermediateRoboticsMini/Robo2s.jpg");
        Robo3s = this.loadImage("/intermediateRoboticsMini/Robo3s.jpg");
        Robo4s = this.loadImage("/intermediateRoboticsMini/Robo4s.jpg");
        Robo5s = this.loadImage("/intermediateRoboticsMini/Robo5s.jpg");
        Robo6s = this.loadImage("/intermediateRoboticsMini/Robo6s.jpg");
        Robo7s = this.loadImage("/intermediateRoboticsMini/Robo7s.jpg");
        Robo8s = this.loadImage("/intermediateRoboticsMini/Robo8s.jpg");
        Robo9s = this.loadImage("/intermediateRoboticsMini/Robo9s.jpg");
        Robo10s = this.loadImage("/intermediateRoboticsMini/Robo10s.jpg");
        Robo11s = this.loadImage("/intermediateRoboticsMini/Robo11s.jpg");
        Robo12s = this.loadImage("/intermediateRoboticsMini/Robo12s.jpg");
        Robo13s = this.loadImage("/intermediateRoboticsMini/Robo13s.jpg");
        Robo14s = this.loadImage("/intermediateRoboticsMini/Robo14s.jpg");
        Robo15s = this.loadImage("/intermediateRoboticsMini/Robo15s.jpg");
        Robo16s = this.loadImage("/intermediateRoboticsMini/Robo16s.jpg");
        Robo17s = this.loadImage("/intermediateRoboticsMini/Robo17s.jpg");
        Robo18s = this.loadImage("/intermediateRoboticsMini/Robo18s.jpg");
        ScratchW1s = this.loadImage("/scratchWorkshopMini/ScratchW1s.jpg");
        ScratchW2s = this.loadImage("/scratchWorkshopMini/ScratchW2s.jpg");
        ScratchW3s = this.loadImage("/scratchWorkshopMini/ScratchW3s.jpg");
        ScratchW4s = this.loadImage("/scratchWorkshopMini/ScratchW4s.jpg");
        ScratchW5s = this.loadImage("/scratchWorkshopMini/ScratchW5s.jpg");
        ScratchW6s = this.loadImage("/scratchWorkshopMini/ScratchW6s.jpg");
        ScratchW7s = this.loadImage("/scratchWorkshopMini/ScratchW7s.jpg");
        ScratchW8s = this.loadImage("/scratchWorkshopMini/ScratchW8s.jpg");
        ScratchW9s = this.loadImage("/scratchWorkshopMini/ScratchW9s.jpg");
        ScratchW10s = this.loadImage("/scratchWorkshopMini/ScratchW10s.jpg");
        ScratchW11s = this.loadImage("/scratchWorkshopMini/ScratchW11s.jpg");
        Math1s = this.loadImage("/introductionMathematicaMini/Math1s.jpg");
        Math2s = this.loadImage("/introductionMathematicaMini/Math2s.jpg");
        Math3s = this.loadImage("/introductionMathematicaMini/Math3s.jpg");
        Art1s = this.loadImage("/artOfCodeMini/Art1s.jpg");
        Art2s = this.loadImage("/artOfCodeMini/Art2s.jpg");
        Art3s = this.loadImage("/artOfCodeMini/Art3s.jpg");
        Art4s = this.loadImage("/artOfCodeMini/Art4s.jpg");
        Art5s = this.loadImage("/artOfCodeMini/Art5s.jpg");
        Art6s = this.loadImage("/artOfCodeMini/Art6s.jpg");
        Robot1s = this.loadImage("/advancedRoboticsMini/Robots (1).jpg");
        Robot2s = this.loadImage("/advancedRoboticsMini/Robots (2).jpg");
        Robot3s = this.loadImage("/advancedRoboticsMini/Robots (3).jpg");
        Robot4s = this.loadImage("/advancedRoboticsMini/Robots (4).jpg");
        Robot5s = this.loadImage("/advancedRoboticsMini/Robots (5).jpg");
        Robot6s = this.loadImage("/advancedRoboticsMini/Robots (6).jpg");
        Robot7s = this.loadImage("/advancedRoboticsMini/Robots (7).jpg");
        Robot8s = this.loadImage("/advancedRoboticsMini/Robots (8).jpg");
        Robot9s = this.loadImage("/advancedRoboticsMini/Robots (9).jpg");
        Robot10s = this.loadImage("/advancedRoboticsMini/Robots (10).jpg");
        Robot11s = this.loadImage("/advancedRoboticsMini/Robots (11).jpg");
        Robot12s = this.loadImage("/advancedRoboticsMini/Robots (12).jpg");
        Robot13s = this.loadImage("/advancedRoboticsMini/Robots (13).jpg");
        Robot14s = this.loadImage("/advancedRoboticsMini/Robots (14).jpg");
        Robot15s = this.loadImage("/advancedRoboticsMini/Robots (15).jpg");
        Robot16s = this.loadImage("/advancedRoboticsMini/Robots (16).jpg");
        Robot17s = this.loadImage("/advancedRoboticsMini/Robots (17).jpg");
        Robot18s = this.loadImage("/advancedRoboticsMini/Robots (18).jpg");
        Robot19s = this.loadImage("/advancedRoboticsMini/Robots (19).jpg");
        Robot20s = this.loadImage("/advancedRoboticsMini/Robots (20).jpg");
        Robot21s = this.loadImage("/advancedRoboticsMini/Robots (21).jpg");
        Robot22s = this.loadImage("/advancedRoboticsMini/Robots (22).jpg");
        Robot23s = this.loadImage("/advancedRoboticsMini/Robots (23).jpg");
        Robot24s = this.loadImage("/advancedRoboticsMini/Robots (24).jpg");
        Robot25s = this.loadImage("/advancedRoboticsMini/Robots (25).jpg");
        Robot26s = this.loadImage("/advancedRoboticsMini/Robots (26).jpg");
        Robot27s = this.loadImage("/advancedRoboticsMini/Robots (27).jpg");
        Robot28s = this.loadImage("/advancedRoboticsMini/Robots (28).jpg");
        Robot29s = this.loadImage("/advancedRoboticsMini/Robots (29).jpg");
        Robot30s = this.loadImage("/advancedRoboticsMini/Robots (30).jpg");
        Robot31s = this.loadImage("/advancedRoboticsMini/Robots (31).jpg");
        Robot32s = this.loadImage("/advancedRoboticsMini/Robots (32).jpg");
        Robot33s = this.loadImage("/advancedRoboticsMini/Robots (33).jpg");
        Robot34s = this.loadImage("/advancedRoboticsMini/Robots (34).jpg");
        Robot35s = this.loadImage("/advancedRoboticsMini/Robots (35).jpg");
        Robot36s = this.loadImage("/advancedRoboticsMini/Robots (36).jpg");
        Robot37s = this.loadImage("/advancedRoboticsMini/Robots (37).jpg");
        Robot38s = this.loadImage("/advancedRoboticsMini/Robots (38).jpg");
        Robot39s = this.loadImage("/advancedRoboticsMini/Robots (39).jpg");
        Robot40s = this.loadImage("/advancedRoboticsMini/Robots (40).jpg");
        Robot41s = this.loadImage("/advancedRoboticsMini/Robots (41).jpg");
        Robot42s = this.loadImage("/advancedRoboticsMini/Robots (42).jpg");
        Robot43s = this.loadImage("/advancedRoboticsMini/Robots (43).jpg");
        Robot44s = this.loadImage("/advancedRoboticsMini/Robots (44).jpg");
        Robot45s = this.loadImage("/advancedRoboticsMini/Robots (45).jpg");
        Robot46s = this.loadImage("/advancedRoboticsMini/Robots (46).jpg");
        Robot47s = this.loadImage("/advancedRoboticsMini/Robots (47).jpg");
        Robot48s = this.loadImage("/advancedRoboticsMini/Robots (48).jpg");
        Robot49s = this.loadImage("/advancedRoboticsMini/Robots (49).jpg");
        Robot50s = this.loadImage("/advancedRoboticsMini/Robots (50).jpg");
        Robot51s = this.loadImage("/advancedRoboticsMini/Robots (51).jpg");
        Robot52s = this.loadImage("/advancedRoboticsMini/Robots (52).jpg");
        Robot53s = this.loadImage("/advancedRoboticsMini/Robots (53).jpg");
        Robot54s = this.loadImage("/advancedRoboticsMini/Robots (54).jpg");
        Robot55s = this.loadImage("/advancedRoboticsMini/Robots (55).jpg");
        Robot56s = this.loadImage("/advancedRoboticsMini/Robots (56).jpg");
        Robot57s = this.loadImage("/advancedRoboticsMini/Robots (57).jpg");
        Robot58s = this.loadImage("/advancedRoboticsMini/Robots (58).jpg");
        Robot59s = this.loadImage("/advancedRoboticsMini/Robots (59).jpg");
        Robot60s = this.loadImage("/advancedRoboticsMini/Robots (60).jpg");
        Robot61s = this.loadImage("/advancedRoboticsMini/Robots (61).jpg");
        Robot62s = this.loadImage("/advancedRoboticsMini/Robots (62).jpg");
        Robot63s = this.loadImage("/advancedRoboticsMini/Robots (63).jpg");
        Robot64s = this.loadImage("/advancedRoboticsMini/Robots (64).jpg");
        Robot65s = this.loadImage("/advancedRoboticsMini/Robots (65).jpg");
        Robot66s = this.loadImage("/advancedRoboticsMini/Robots (66).jpg");
        AppW1s = this.loadImage("/appInventorWorkshopMini/AppW1s.jpg");
        AppW2s = this.loadImage("/appInventorWorkshopMini/AppW2s.jpg");
        AppW3s = this.loadImage("/appInventorWorkshopMini/AppW3s.jpg");
        AppW4s = this.loadImage("/appInventorWorkshopMini/AppW4s.jpg");
        AppW5s = this.loadImage("/appInventorWorkshopMini/AppW5s.jpg");
        AppW6s = this.loadImage("/appInventorWorkshopMini/AppW6s.jpg");
        AppW7s = this.loadImage("/appInventorWorkshopMini/AppW7s.jpg");
        AppW8s = this.loadImage("/appInventorWorkshopMini/AppW8s.jpg");
    }

    public BufferedImage loadImage(String path) {
        BufferedImage image = null;
        try {
            image = ImageIO.read(this.getClass().getResourceAsStream(path));
            image.setAccelerationPriority(1);
        } catch (IOException e) {
            e.printStackTrace();
        }
        return image;
    }

}
