package source;

enum Screen {

	/*
	 * This class holds the Screens that are checked for each frame
	 * 
	 * 
	 */
	STARTINGSCREEN, INTERNSCREEN, WORKSHOPSCREEN, SCREEN1, SCREEN1P, SCREEN2, SCREEN3, SCREEN4, SCREEN5, SCREEN6, SCREEN7, SCREEN8, SCREEN9, SCREEN10, SCREEN11, SCREEN12, SCREEN13, SCREEN14, SCREEN15, SCREEN16, SCREEN17;

}
